# Bag of words

## We will use a spam classification dataset for this practical

In [45]:
import nltk
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer

from sklearn.feature_extraction.text import CountVectorizer

stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/vedanshdwivedi/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [31]:
messages = pd.read_csv("../datasets/spam.csv", encoding="latin-1")
messages = messages[["v1", "v2"]]
messages = messages.rename(columns={"v1": "label", "v2": "message"})
df = messages.copy()
messages.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [37]:
# Data Cleaning and Preprocessing

# Lowercase chars
# Remove special chars
# Remove stop words
# Apply stemming
 
corpus = []
for i in range(len(messages)):
    label, message = messages.iloc[i]
    lowercaseMessage = message.lower()
    cleanMessage = re.sub(r'[^a-zA-Z0-9]', ' ', lowercaseMessage)
    tokenizedWords = nltk.word_tokenize(cleanMessage)
    stemmedWords = [lemmatizer.lemmatize(x) for x in tokenizedWords]
    removedStopWords = [x for x in stemmedWords if x not in stopwords.words("english")]
    joinedSentence = " ".join(removedStopWords)
    corpus.append(joinedSentence)

df["processed_message"] = corpus
df.head()

,label,message,processed_message
0,ham,"Go until jurong point, crazy.. Available only ...",go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry 2 wkly comp win fa cup final tkts 2...
3,ham,U dun say so early hor... U c already then say...,u dun say early hor u c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah think go usf life around though

In [57]:
enableBinaryBagOfWords = True
vectorizer = CountVectorizer(max_features=2500, binary=enableBinaryBagOfWords)
X = vectorizer.fit_transform(corpus).toarray()
X.shape

(5572, 2500)