# Spam Classification

We will use a spam classification dataset for this practical. This also will cover the following topics:
1. Bag of words
2. N-grams
3. TF-IDF
4. word2vec

In [14]:
import nltk
import pandas as pd
import numpy as np
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/vedanshdwivedi/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
messages = pd.read_csv("../datasets/spam.csv", encoding="latin-1")
messages = messages[["v1", "v2"]]
messages = messages.rename(columns={"v1": "label", "v2": "message"})
df = messages.copy()
messages.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
# Data Cleaning and Preprocessing

# Lowercase chars
# Remove special chars
# Remove stop words
# Apply stemming
 
corpus = []
for i in range(len(messages)):
    label, message = messages.iloc[i]
    lowercaseMessage = message.lower()
    cleanMessage = re.sub(r'[^a-zA-Z0-9]', ' ', lowercaseMessage)
    tokenizedWords = nltk.word_tokenize(cleanMessage)
    stemmedWords = [lemmatizer.lemmatize(x) for x in tokenizedWords]
    removedStopWords = [x for x in stemmedWords if x not in stopwords.words("english")]
    joinedSentence = " ".join(removedStopWords)
    corpus.append(joinedSentence)

df["processed_message"] = corpus
df.head()

,label,message,processed_message
0,ham,"Go until jurong point, crazy.. Available only ...",go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry 2 wkly comp win fa cup final tkts 2...
3,ham,U dun say so early hor... U c already then say...,u dun say early hor u c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah think go usf life around though

In [4]:
enableBinaryBagOfWords = True
vectorizer = CountVectorizer(max_features=500, binary=enableBinaryBagOfWords, ngram_range=(2,3))
X = vectorizer.fit_transform(corpus).toarray()
X.shape

(5572, 500)

In [5]:
vectorizer.vocabulary_

{'free entry': np.int64(168),
 'rate apply': np.int64(355),
 'claim call': np.int64(107),
 'claim code': np.int64(108),
 'update latest': np.int64(445),
 'latest colour': np.int64(243),
 'free call': np.int64(165),
 'call mobile': np.int64(85),
 'update latest colour': np.int64(446),
 'call mobile update': np.int64(86),
 'gon na': np.int64(188),
 'chance win': np.int64(103),
 'txt word': np.int64(438),
 'dont miss': np.int64(146),
 'let know': np.int64(245),
 'feel like': np.int64(159),
 'go home': np.int64(184),
 'anything lor': np.int64(58),
 'mobile free': np.int64(289),
 'free camcorder': np.int64(166),
 'please call': np.int64(332),
 'call 08000930705': np.int64(78),
 'delivery tomorrow': np.int64(142),
 'lt gt': np.int64(262),
 'missed call': np.int64(286),
 'want go': np.int64(479),
 'first time': np.int64(162),
 'like lt': np.int64(248),
 'like lt gt': np.int64(249),
 'sm ac': np.int64(384),
 'bx420 ip4': np.int64(76),
 'ip4 5we': np.int64(230),
 'bx420 ip4 5we': np.int64(77),
 'sorry call': np.int64(388),
 'call later': np.int64(84),
 'later meeting': np.int64(241),
 'sorry call later': np.int64(389),
 'prize call': np.int64(350),
 'ur awarded': np.int64(449),
 'hi babe': np.int64(218),
 'wan na': np.int64(476),
 'call free': np.int64(83),
 'thats cool': np.int64(417),
 'hi hi': np.int64(220),
 'got ta': np.int64(195),
 'call customer': np.int64(81),
 'customer service': np.int64(134),
 'service representative': np.int64(379),
 'guaranteed 1000': np.int64(202),
 '1000 cash': np.int64(14),
 '5000 prize': np.int64(44),
 'please call customer': np.int64(333),
 'call customer service': np.int64(82),
 'customer service representative': np.int64(136),
 'guaranteed 1000 cash': np.int64(203),
 'get home': np.int64(174),
 'trying contact': np.int64(430),
 'draw show': np.int64(149),
 'prize guaranteed': np.int64(353),
 'guaranteed call': np.int64(204),
 'valid 12hrs': np.int64(469),
 '12hrs 150ppm': np.int64(18),
 'prize guaranteed call': np.int64(354),
 'valid 12hrs 150ppm': np.int64(470),
 'said happy': np.int64(372),
 'happy day': np.int64(213),
 'specially selected': np.int64(395),
 'selected receive': np.int64(376),
 'speak live': np.int64(391),
 'live operator': np.int64(253),
 'operator claim': np.int64(321),
 'specially selected receive': np.int64(396),
 'speak live operator': np.int64(392),
 'live operator claim': np.int64(254),
 'account statement': np.int64(53),
 'identifier code': np.int64(228),
 'urgent mobile': np.int64(462),
 'awarded 2000': np.int64(66),
 'bonus caller': np.int64(70),
 'caller prize': np.int64(90),
 'bonus caller prize': np.int64(71),
 'number ending': np.int64(314),
 'receive 350': np.int64(357),
 '350 award': np.int64(39),
 'match please': np.int64(276),
 'receive 350 award': np.int64(358),
 'match please call': np.int64(277),
 'wat time': np.int64(481),
 'give call': np.int64(181),
 'ur mob': np.int64(456),
 'join uk': np.int64(231),
 'gud ni8': np.int64(206),
 'per msg': np.int64(325),
 'reply stop': np.int64(363),
 'new year': np.int64(305),
 'reply yes': np.int64(364),
 'www sm': np.int64(496),
 'stop send': np.int64(397),
 'send stop': np.int64(378),
 'www sm ac': np.int64(497),
 'stop send stop': np.int64(398),
 'ur mobile': np.int64(458),
 'urgent trying': np.int64(466),
 'urgent trying contact': np.int64(467),
 'co uk': np.int64(113),
 'keep touch': np.int64(232),
 'gud mrng': np.int64(205),
 'nice day': np.int64(307),
 'see tomorrow': np.int64(375),
 'lt decimal': np.int64(260),
 'decimal gt': np.int64(139),
 'lt decimal gt': np.int64(261),
 'like dat': np.int64(246),
 'get ready': np.int64(175),
 'hope great': np.int64(225),
 'txt nokia': np.int64(436),
 'good morning': np.int64(192),
 'ur friend': np.int64(452),
 'secret admirer': np.int64(373),
 'admirer looking': np.int64(56),
 'looking make': np.int64(256),
 'make contact': np.int64(272),
 'contact find': np.int64(122),
 'find reveal': np.int64(160),
 'reveal think': np.int64(365),
 'think ur': np.int64(418),
 'ur special': np.int64(460),
 'special call': np.int64(394),
 'secret admirer looking': np.int64(374),
 'admirer looking make': np.int64(57),
 'looking make contact': np.int64(257),
 'make contact find': np.int64(273),
 'contact find reveal': np.int64(123),
 'find reveal think': np.int64(161),
 'reveal think ur': np.int64(366),
 'think ur special': np.int64(419),
 'ur special call': np.int64(461),
 'good night': np.int64(194),
 'congratulation ur': np.int64(120),
 '500 cd': np.int64(41),
 'entry 100': np.int64(154),
 'draw txt': np.int64(150),
 'txt music': np.int64(434),
 'music 87066': np.int64(297),
 'www ldew': np.int64(495),
 'congratulation ur awarded': np.int64(121),
 'free entry 100': np.int64(169),
 'draw txt music': np.int64(151),
 'txt music 87066': np.int64(435),
 'lem know': np.int64(244),
 'get back': np.int64(172),
 'tried contact': np.int64(429),
 '750 anytime': np.int64(46),
 'anytime network': np.int64(59),
 'network min': np.int64(301),
 'camcorder reply': np.int64(91),
 'reply call': np.int64(361),
 '750 anytime network': np.int64(47),
 'anytime network min': np.int64(60),
 'camcorder reply call': np.int64(92),
 'reply call 08000930705': np.int64(362),
 'text stop': np.int64(415),
 '500 pound': np.int64(42),
 'last night': np.int64(239),
 'camera phone': np.int64(93),
 'cant pick': np.int64(94),
 'pick phone': np.int64(330),
 'phone right': np.int64(328),
 'right pls': np.int64(367),
 'pls send': np.int64(336),
 'send message': np.int64(377),
 'cant pick phone': np.int64(95),
 'pick phone right': np.int64(331),
 'phone right pls': np.int64(329),
 'right pls send': np.int64(368),
 'pls send message': np.int64(337),
 'po box': np.int64(338),
 'great day': np.int64(196),
 'babe love': np.int64(67),
 'love ya': np.int64(259),
 'per minute': np.int64(324),
 'valentine day': np.int64(468),
 '150p msg': np.int64(23),
 'msg rcvd': np.int64(295),
 'cost 50': np.int64(126),
 'ur cash': np.int64(450),
 'cash balance': np.int64(100),
 'balance currently': np.int64(68),
 'currently 500': np.int64(133),
 'pound maximize': np.int64(344),
 'maximize ur': np.int64(280),
 'cash send': np.int64(102),
 '86688 150p': np.int64(51),
 'hg suite342': np.int64(216),
 'suite342 2lands': np.int64(402),
 '2lands row': np.int64(33),
 'row w1j6hl': np.int64(370),
 'cash balance currently': np.int64(101),
 'balance currently 500': np.int64(69),
 'pound maximize ur': np.int64(345),
 'maximize ur cash': np.int64(281),
 'ur cash send': np.int64(451),
 '86688 150p msg': np.int64(52),
 'hg suite342 2lands': np.int64(217),
 'suite342 2lands row': np.int64(403),
 '2lands row w1j6hl': np.int64(34),
 'good afternoon': np.int64(189),
 'take care': np.int64(405),
 'double min': np.int64(148),
 'call mobileupd8': np.int64(87),
 'mobileupd8 08000839402': np.int64(292),
 '08000839402 call2optout': np.int64(8),
 'call mobileupd8 08000839402': np.int64(88),
 'mobileupd8 08000839402 call2optout': np.int64(293),
 'gt min': np.int64(199),
 'lt gt min': np.int64(265),
 'ringtone order': np.int64(369),
 'per week': np.int64(326),
 'half price': np.int64(210),
 'line rental': np.int64(252),
 'phone free': np.int64(327),
 'call back': np.int64(80),
 'good evening': np.int64(191),
 'na get': np.int64(298),
 'txt stop': np.int64(437),
 'dating service': np.int64(137),
 'dont want': np.int64(147),
 'last week': np.int64(240),
 'mobile number': np.int64(290),
 'number ha': np.int64(315),
 'ha awarded': np.int64(208),
 '2000 prize': np.int64(26),
 'land line': np.int64(234),
 'line claim': np.int64(250),
 'claim 3030': np.int64(105),
 '3030 valid': np.int64(37),
 'urgent mobile number': np.int64(463),
 'mobile number ha': np.int64(291),
 'number ha awarded': np.int64(316),
 'ha awarded 2000': np.int64(209),
 '2000 prize guaranteed': np.int64(27),
 'land line claim': np.int64(235),
 'line claim 3030': np.int64(251),
 'claim 3030 valid': np.int64(106),
 '3030 valid 12hrs': np.int64(38),
 'watching tv': np.int64(482),
 'gt th': np.int64(201),
 'lt gt th': np.int64(267),
 'gt lt': np.int64(197),
 'lt gt dollar': np.int64(263),
 'lt gt lt': np.int64(264),
 'gt lt gt': np.int64(198),
 'well done': np.int64(488),
 'hope good': np.int64(224),
 'good day': np.int64(190),
 'text back': np.int64(410),
 'tenerife holiday': np.int64(409),
 'holiday 5000': np.int64(223),
 '5000 cash': np.int64(43),
 'award call': np.int64(65),
 'cant wait': np.int64(96),
 'free text': np.int64(171),
 'meeting call': np.int64(282),
 'prize claim': np.int64(351),
 '40gb ipod': np.int64(40),
 'http www': np.int64(227),
 '000 bonus': np.int64(2),
 '03 2nd': np.int64(6),
 '2nd attempt': np.int64(35),
 'attempt contact': np.int64(62),
 '000 bonus caller': np.int64(3),
 '03 2nd attempt': np.int64(7),
 '2nd attempt contact': np.int64(36),
 'claim ur': np.int64(111),
 'ur 150': np.int64(447),
 '150 worth': np.int64(21),
 'worth discount': np.int64(491),
 'discount voucher': np.int64(144),
 'text yes': np.int64(416),
 '85023 savamob': np.int64(50),
 'offer mobile': np.int64(317),
 '00 sub': np.int64(0),
 'sub 16': np.int64(401),
 'claim ur 150': np.int64(112),
 'ur 150 worth': np.int64(448),
 '150 worth discount': np.int64(22),
 'worth discount voucher': np.int64(492),
 '00 sub 16': np.int64(1),
 'private 2003': np.int64(348),
 '2003 account': np.int64(28),
 'show 800': np.int64(381),
 '800 un': np.int64(48),
 'un redeemed': np.int64(443),
 'redeemed point': np.int64(359),
 'point call': np.int64(342),
 'private 2003 account': np.int64(349),
 '2003 account statement': np.int64(29),
 'show 800 un': np.int64(382),
 '800 un redeemed': np.int64(49),
 'un redeemed point': np.int64(444),
 'redeemed point call': np.int64(360),
 'go day': np.int64(183),
 'kiss across': np.int64(233),
 'across sea': np.int64(55),
 'later tonight': np.int64(242),
 'happy birthday': np.int64(212),
 '000 cash': np.int64(4),
 'new video': np.int64(303),
 'video phone': np.int64(471),
 'new video phone': np.int64(304),
 'one day': np.int64(320),
 'shopping spree': np.int64(380),
 'customer service announcement': np.int64(135),
 'ok lor': np.int64(319),
 'want come': np.int64(478),
 'make sure': np.int64(274),
 'stop text': np.int64(399),
 'account statement show': np.int64(54),
 'going home': np.int64(186),
 'every week': np.int64(155),
 'come home': np.int64(117),
 'pls call': np.int64(334),
 'cash 2000': np.int64(97),
 '1000 cash 2000': np.int64(15),
 'offer new': np.int64(318),
 'day send': np.int64(138),
 'next week': np.int64(306),
 'happy new': np.int64(214),
 'happy new year': np.int64(215),
 'every wk': np.int64(157),
 'wk txt': np.int64(490),
 'every wk txt': np.int64(158),
 'gt minute': np.int64(200),
 'lt gt minute': np.int64(266),
 'national rate': np.int64(299),
 'lt time': np.int64(268),
 'time gt': np.int64(420),
 'lt time gt': np.int64(269),
 'free 1st': np.int64(163),
 '1st week': np.int64(24),
 'week no1': np.int64(483),
 'no1 nokia': np.int64(308),
 'nokia tone': np.int64(310),
 'tone ur': np.int64(427),
 'week txt': np.int64(485),
 'get txting': np.int64(176),
 'txting tell': np.int64(439),
 'tell ur': np.int64(407),
 'ur mate': np.int64(455),
 'mate www': np.int64(278),
 'www getzed': np.int64(493),
 'getzed co': np.int64(178),
 'uk pobox': np.int64(441),
 'pobox 36504': np.int64(340),
 'free 1st week': np.int64(164),
 '1st week no1': np.int64(25),
 'week no1 nokia': np.int64(484),
 'no1 nokia tone': np.int64(309),
 'nokia tone ur': np.int64(311),
 'every week txt': np.int64(156),
 'week txt nokia': np.int64(486),
 'get txting tell': np.int64(177),
 'txting tell ur': np.int64(440),
 'tell ur mate': np.int64(408),
 'mate www getzed': np.int64(279),
 'www getzed co': np.int64(494),
 'getzed co uk': np.int64(179),
 'co uk pobox': np.int64(114),
 'uk pobox 36504': np.int64(442),
 'pobox 36504 w45wq': np.int64(341),
 'gift voucher': np.int64(180),
 '100 weekly': np.int64(13),
 'weekly draw': np.int64(487),
 'morning dear': np.int64(294),
 'good morning dear': np.int64(193),
 'landline complimentary': np.int64(236),
 'holiday 10': np.int64(221),
 '10 000': np.int64(9),
 'cash await': np.int64(98),
 'await collection': np.int64(63),
 'collection sae': np.int64(115),
 'holiday 10 000': np.int64(222),
 '10 000 cash': np.int64(10),
 '000 cash await': np.int64(5),
 'cash await collection': np.int64(99),
 'await collection sae': np.int64(64),
 'wan go': np.int64(474),
 '100 free': np.int64(11),
 'price line': np.int64(346),
 '100 free text': np.int64(12),
 'half price line': np.int64(211),
 'price line rental': np.int64(347),
 'dont know': np.int64(145),
 'text call': np.int64(411),
 'call 08712460324': np.int64(79),
 '10p min': np.int64(16),
 'stop text call': np.int64(400),
 'text call 08712460324': np.int64(412),
 'contact today': np.int64(124),
 'today draw': np.int64(424),
 'trying contact today': np.int64(431),
 'contact today draw': np.int64(125),
 'today draw show': np.int64(425),
 'come back': np.int64(116),
 'wait till': np.int64(473),
 'call tomorrow': np.int64(89),
 'mob every': np.int64(287),
 'tone 16': np.int64(426),
 'tone ur mob': np.int64(428),
 'ur mob every': np.int64(457),
 'mob every week': np.int64(288),
 'gud nyt': np.int64(207),
 'someone know': np.int64(387),
 'win 100': np.int64(489),
 'txt chat': np.int64(432),
 'chat 86688': np.int64(104),
 'txt chat 86688': np.int64(433),
 'digital camera': np.int64(143),
 'landline delivery': np.int64(237),
 'landline delivery within': np.int64(238),
 'sorry da': np.int64(390),
 'important information': np.int64(229),
 'log onto': np.int64(255),
 'www urawinner': np.int64(498),
 'www urawinner com': np.int64(499),
 'w1j6hl ldn': np.int64(472),
 'row w1j6hl ldn': np.int64(371),
 'take part': np.int64(406),
 'ur home': np.int64(453),
 'min stop': np.int64(285),
 'ur smile': np.int64(459),
 '20p per': np.int64(30),
 'per min': np.int64(322),
 'min ntt': np.int64(283),
 'ntt ltd': np.int64(312),
 'ltd po': np.int64(270),
 'box 1327': np.int64(72),
 '1327 croydon': np.int64(19),
 'croydon cr9': np.int64(131),
 'cr9 5wb': np.int64(129),
 '5wb 0870': np.int64(45),
 '20p per min': np.int64(31),
 'per min ntt': np.int64(323),
 'min ntt ltd': np.int64(284),
 'ntt ltd po': np.int64(313),
 'ltd po box': np.int64(271),
 'po box 1327': np.int64(339),
 'box 1327 croydon': np.int64(73),
 '1327 croydon cr9': np.int64(20),
 'croydon cr9 5wb': np.int64(132),
 'cr9 5wb 0870': np.int64(130),
 'sweet dream': np.int64(404),
 'go back': np.int64(182),
 '250 cash every': np.int64(32),
 'wan meet': np.int64(475),
 'national rate call': np.int64(300),
 'bt national': np.int64(74),
 'bt national rate': np.int64(75),
 'pls pls': np.int64(335),
 'go well': np.int64(185),
 'new nokia': np.int64(302),
 'wan watch': np.int64(477),
 'around lt': np.int64(61),
 'ur life': np.int64(454),
 'coming home': np.int64(119),
 'free msg': np.int64(170),
 'dun wan': np.int64(152),
 'come tomorrow': np.int64(118),
 'claim easy': np.int64(109),
 'easy call': np.int64(153),
 '10p per': np.int64(17),
 'prize claim easy': np.int64(352),
 'claim easy call': np.int64(110),
 'love amp': np.int64(258),
 'urgent please': np.int64(464),
 'urgent please call': np.int64(465),
 'costa del': np.int64(127),
 'del sol': np.int64(140),
 'sol holiday': np.int64(385),
 'toclaim sae': np.int64(421),
 'costa del sol': np.int64(128),
 'del sol holiday': np.int64(141),
 'sol holiday 5000': np.int64(386),
 'toclaim sae tc': np.int64(422),
 'sk38xh cost 50': np.int64(383),
 'going sleep': np.int64(187),
 'speak soon': np.int64(393),
 'hi darlin': np.int64(219),
 'get free': np.int64(173),
 'today birthday': np.int64(423),
 'like hour': np.int64(247),
 'man wa': np.int64(275),
 'murdered lt': np.int64(296),
 'house maid': np.int64(226),
 'post office': np.int64(343),
 'want new': np.int64(480),
 'text free': np.int64(413),
 'text free camcorder': np.int64(414),
 'free camcorder reply': np.int64(167),
 'really need': np.int64(356)}

In [18]:
## TF-IDF
tfVectorizer = TfidfVectorizer(max_features=100, ngram_range=(2,2))
X = tfVectorizer.fit_transform(corpus).toarray()
X.shape

(5572, 100)

In [19]:
# This will change the settings so if we print the array, it will round off to 3 decimal places
np.set_printoptions(edgeitems=30, linewidth=1000000, formatter=dict(float=lambda x: "%.3g" % x))
tfVectorizer.vocabulary_

{'free entry': np.int64(31),
 'claim call': np.int64(17),
 'free call': np.int64(30),
 'gon na': np.int64(35),
 'chance win': np.int64(16),
 'txt word': np.int64(87),
 'let know': np.int64(55),
 'please call': np.int64(67),
 'call 08000930705': np.int64(10),
 'lt gt': np.int64(59),
 'want go': np.int64(97),
 'like lt': np.int64(56),
 'sm ac': np.int64(79),
 'sorry call': np.int64(80),
 'call later': np.int64(12),
 'ur awarded': np.int64(88),
 'wan na': np.int64(95),
 'hi hi': np.int64(49),
 'got ta': np.int64(39),
 'call customer': np.int64(11),
 'customer service': np.int64(22),
 'guaranteed 1000': np.int64(43),
 '1000 cash': np.int64(0),
 'trying contact': np.int64(84),
 'draw show': np.int64(27),
 'prize guaranteed': np.int64(73),
 'guaranteed call': np.int64(44),
 'valid 12hrs': np.int64(94),
 'selected receive': np.int64(75),
 'account statement': np.int64(7),
 'identifier code': np.int64(52),
 'urgent mobile': np.int64(93),
 '350 award': np.int64(6),
 'wat time': np.int64(98),
 'ur mob': np.int64(91),
 'gud ni8': np.int64(46),
 'new year': np.int64(62),
 'send stop': np.int64(77),
 'ur mobile': np.int64(92),
 'co uk': np.int64(19),
 'gud mrng': np.int64(45),
 'nice day': np.int64(63),
 'lt decimal': np.int64(58),
 'decimal gt': np.int64(24),
 'txt nokia': np.int64(85),
 'good morning': np.int64(37),
 'ur friend': np.int64(90),
 'good night': np.int64(38),
 'get back': np.int64(33),
 'reply call': np.int64(74),
 'last night': np.int64(54),
 'camera phone': np.int64(14),
 'cant pick': np.int64(15),
 'pick phone': np.int64(66),
 'pls send': np.int64(68),
 'send message': np.int64(76),
 'po box': np.int64(69),
 'great day': np.int64(40),
 '150p msg': np.int64(1),
 'ur cash': np.int64(89),
 'suite342 2lands': np.int64(81),
 '2lands row': np.int64(4),
 'good afternoon': np.int64(36),
 'take care': np.int64(82),
 'double min': np.int64(26),
 'call mobileupd8': np.int64(13),
 'gt min': np.int64(42),
 'txt stop': np.int64(86),
 'dating service': np.int64(23),
 'mobile number': np.int64(60),
 '2000 prize': np.int64(2),
 'land line': np.int64(53),
 'line claim': np.int64(57),
 'gt lt': np.int64(41),
 'hope good': np.int64(50),
 'free text': np.int64(32),
 'prize claim': np.int64(72),
 'http www': np.int64(51),
 '2nd attempt': np.int64(5),
 'attempt contact': np.int64(8),
 'claim ur': np.int64(18),
 'private 2003': np.int64(71),
 '2003 account': np.int64(3),
 'show 800': np.int64(78),
 'point call': np.int64(70),
 'happy birthday': np.int64(47),
 'ok lor': np.int64(65),
 'want come': np.int64(96),
 'every week': np.int64(29),
 'come home': np.int64(21),
 'happy new': np.int64(48),
 'national rate': np.int64(61),
 'nokia tone': np.int64(64),
 'week txt': np.int64(99),
 'tell ur': np.int64(83),
 'gift voucher': np.int64(34),
 'await collection': np.int64(9),
 'dont know': np.int64(25),
 'come back': np.int64(20),
 'dun wan': np.int64(28)}